[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
rustflags = [
    "--cfg",
    "espidf_time64",
]

[env]
MCU = "esp32s3"
ESP_IDF_SYS_ROOT_CRATE = "usb2ble-fw"
IDF_PATH = "/Users/alex/Developer/T2/T2/.embuild/espressif/esp-idf/master"
